seed: 111
env_init_seed: 1
eval_init_seed: 2

num_train_steps: 20000
num_envs: 128

agent:
  learning_rate: 1e-3
  baseline_learning_rate: 3e-4
  tlm_backward_learning_rate: 1e-4
  logZ_learning_rate: 1e-1
  weight_decay: 0.0
  start_eps: 0.0
  end_eps: 0.0
  exploration_steps: 0 # Should be <= of num_train_steps
  ppo_policy_epochs: 4
  ppo_baseline_epochs: 4
  ppo_baseline_num_splits: 2
  tlm_epochs: 4
  clip_eps: 0.2
  train_backward: false
  anneal_beta: true

network:
  num_heads: 4
  num_layers: 2
  embedding_size: 64
  hidden_size: 64
  intermediate_size: 64
  dropout_rate: 0.0
  attention_dropout_rate: 0.0

environment:
  L: 16
  beta: 0.6
  k: 8

metrics:
  n_rounds: 16
  batch_size: 128
  eubo_batch_size: 128
  n_gt_samples: 2048
  gt_burn_in: 2000
  gt_sweeps_per_sample: 5
  sinkhorn_reg: 0.001
  sinkhorn_iters: 200
  n_final_gt_samples: 16384
  n_final_eubo_samples: 2048
  n_final_rounds: 32

logging:
  track_each: 100 # in terms of total training steps, not divided by num_envs
  eval_each: 500 # in terms of total training steps, not divided by num_envs
  metric_buffer_size: 200000
  tqdm_print_rate: 100
  use_writer: true
  log_dir: null # If null, dir will be automatically created
  checkpoint_dir: null # If null, dir will be automatically created
# Technical information for writer
writer:
  writer_type: comet_ml # wandb, trackio or null (no logging online)
  save_locally: false # Save metrics locally or not
  entity: azykova-myzina
  project: ising

# Technical information for hydra
hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S} 